const productos = [
    {id:01, tipo:"perifericos", nombre:"Mouse logitech", precio: 4400, foto: "./imagenes/1.png" },
    {id:02, tipo:"perifericos", nombre:"Auriculares sony", precio: 9500, foto: "./imagenes/2.png" },
    {id:03, tipo:"perifericos", nombre:"auriculares motorola", precio: 1000, foto: "./imagenes/3.png" },
    {id:04, tipo:"perifericos", nombre:"mouse genius", precio: 1500, foto: "./imagenes/34.png" },
    {id:05, tipo:"perifericos", nombre:"teclado logitech", precio: 14000, foto: "./imagenes/25.png" },
    {id:06, tipo:"perifericos", nombre:"teclado logitech", precio: 1500, foto: "./imagenes/32.png" },
    {id:07, tipo: "componentes", nombre: "Ryzen 5", precio: 45000, foto: "./imagenes/4.png"},
    {id:08, tipo: "componentes", nombre: "Ryzen 3", precio: 38000, foto: "./imagenes/51.png"},
    {id:09, tipo: "componentes", nombre: "intel i3", precio: 38000, foto: "./imagenes/52.png"},
    {id:10, tipo: "componentes", nombre: "placa de video aorus", precio: 380000, foto: "./imagenes/28.png"},
    {id:11, tipo: "componentes", nombre: "core i3", precio: 19000, foto: "./imagenes/54.png"},
    {id:12, tipo: "componentes", nombre: "placa de video gigabyte", precio: 120000, foto: "./imagenes/16.png"},
    {id:13, tipo: "componentes", nombre: "placa de video aorus", precio: 400000, foto: "./imagenes/9.png"},
    {id:14, tipo: "componentes", nombre: "Ryzen 9", precio: 63000, foto: "./imagenes/20.png"},
    {id:15, tipo: "notebook", nombre: "notebook samsung", precio: 230000, foto: "./imagenes/6.png"},
    {id:16, tipo: "notebook", nombre: "notebook razer", precio: 2400, foto: "./imagenes/38.png"},
    {id:17, tipo: "notebook", nombre: "notebook hp", precio: 800, foto: "./imagenes/37.png"},
    {id:18, tipo: "notebook", nombre: "notebook asus", precio: 800, foto: "./imagenes/36.png"}
];